# Generated by Django 3.1.2 on 2020-11-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201115_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_following',
            old_name='person',
            new_name='user_A',
        ),
        migrations.RenameField(
            model_name='user_following',
            old_name='following_person',
            new_name='user_B',
        ),
    ]
